# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Patrick Bryant
email: patrick.bryant@scilifelab.se
description: > # this means to ignore newlines until "baseurl:"
  Code for various applied deep learning projects in bioinformatics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/patrickbryant1/patrickbryant1.github.io" # the base hostname & protocol for your site
github_username:  patrickbryant1
remot_theme: mmistakes/minimal-mistakes
# Build settings
markdown: kramdown
remote_theme: benbalter/retlab
